app:
  port: 8080

database:
  host: localhost
  port: 5432
  user: root
  password: ecommerce
  name: ecommerce_db

redis:
  host: localhost
  port: 6379
  password: redispass

secret:
  jwt: your_jwt_secret_key